name: CI - Test build

on:
  push:
    branches:
      - main

jobs:
  env:
    DB_HOST: ${{ secrets.DB_HOST }}
    DB_USER: ${{ secrets.DB_USER }}
    DB_PORT: ${{secrets.DB_PORT}}
    DB_PASSWORD: ${{secrets.DB_PASSWORD}}
    DB_NAME: ${{secrets.DB_NAME}}

  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t fastapi-ci .

      - name: Runs Docker image as test
        run: |
          docker run -d --name test -p 8000:8000 -e DB_HOST=$DB_HOST -e DB_USER=$DB_USER -e DB_PORT=$DB_PORT -e DB_PASSWORD=$DB_PASSWORD -e DB_NAME=$DB_NAME fastapi-ci
          sleep 5
          docker logs test
          docker stop test